=== think-framework/think-generator/generator-fx/src/main/resources/io/github/thinkframework/generator/beans/factory/xml/think-generator.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://thinkframework.github.io/schema/generators"
            targetNamespace="http://thinkframework.github.io/schema/generators"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">
    <xsd:annotation>
        <xsd:documentation>
            参考NamespaceHandlerSupport实现的配置文件
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="generator">
        <xsd:complexType>
            <xsd:sequence>
                </xsd:element>
                <xsd:element ref="configuration">
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>
                        和Spring的id节点相同
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="clazz" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>
                        和Spring的id节点相同
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="configuration">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="frameName" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            系统引用的框架包的名称
                            例如:org.apache.commons
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="companyName" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            公司名称,包名的一部分
                            例如:org.think
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="appName" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            应用名称,包名的一部分
                            例如:app
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="moduleName" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            模块名称,作为包的后缀名称
                            例如:auth
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="authorName" type="xsd:string" default="unascribed">
                    <xsd:annotation>
                        <xsd:documentation>
                            javaDoc中author节点的名字
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="namespace" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            Struts2,Spring Mvc放置页面的位置
                            Angualr不需要.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="template" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            模板目录
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="extensions" minOccurs="0">
                    <xsd:annotation>
                        <xsd:documentation>
                            javaDoc中author节点的名字
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:element ref="list" minOccurs="0"/>
                            <xsd:element ref="set" minOccurs="0"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="converts" minOccurs="0">
                    <xsd:annotation>
                        <xsd:documentation>
                            需要转换的类型
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:element ref="map" minOccurs="0"/>
                            <xsd:element ref="props" minOccurs="0"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="provider" minOccurs="0">
                    <xsd:annotation>
                        <xsd:documentation>
                            移除表名前缀
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:element ref="list" minOccurs="0"/>
                            <xsd:element ref="set" minOccurs="0"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="prefixs">
                    <xsd:annotation>
                        <xsd:documentation>
                            移除表名前缀
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:element ref="list" minOccurs="0"/>
                            <xsd:element ref="set" minOccurs="0"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="ignores">
                    <xsd:annotation>
                        <xsd:documentation>
                            需要忽略的字段
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element ref="list" minOccurs="0"/>
                            <xsd:element ref="set" minOccurs="0"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="output" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            输出目录
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- type -->
    <xsd:complexType name="entity">
        <xsd:attribute name="key" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="list">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="value" type="xsd:string" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="set">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="value" type="xsd:string" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="map">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="entity" type="entity" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="props">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="prop" maxOccurs="unbounded">
                    <xsd:complexType mixed="true">
                        <xsd:attribute name="key" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== think-framework/think-generator/generator-fx/src/test/resources/applicationContext-generator.xml
<?xml version="1.0" encoding="UTF-8"?>
<generator xmlns="http://thinkframework.github.io/schema/generator"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:beans="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
           http://thinkframework.github.io/schema/generator
           http://thinkframework.github.io/schema/generator/think-generator.xsd" id="generator">
    <description>
        会对configuration下的所有字段生成两个节点,放到生成器上下文中
            例如: companyName会生成:
                companyName: com.glodon.bim5d
                companyName_path: com/glodon/bim5d
        packageName = companyName + appName + moduleName
    </description>
    <configuration>
        <!-- 框架包的名称 -->
        <frameName>com.glodon.bim5d</frameName>
        <!--#公司名称-->
        <companyName>com.glodon.bim5d</companyName>
        <!--#应用名称-->
        <appName>app</appName>
        <!--#模块名称-->
        <!--<moduleName>auth</moduleName>-->
        <!--<moduleName>param</moduleName>-->
        <!--            <moduleName>costenterprise</moduleName>-->
        <moduleName>costproject</moduleName>
        <!--#作者名称-->
        <!--<authorName>lixiaobin</authorName>-->
        <authorName>unascribed</authorName>
        <!--#jsp namespace: web/${namespace}/${className}/get:jsp-->
        <namespace>views</namespace>
        <!--#模板目录-->
        <!--            <template>template/glodon/enterprise</template>-->
        <!--            <template>template/glodon/project</template>-->
        <template>template/test</template>
        <!--#过滤文件-->
        <extensions>
            <list>
                <value>java</value>
                <value>js</value>
                <value>jsp</value>
                <value>xml</value>
                <value>ts</value>
                <value>html</value>
                <value>json</value>
                <value>sql</value>
            </list>
        </extensions>
        <converts>
            <map>
                <entity key="java.sql.Types.BIGINT" value="java.math.BigInteger"/>
                <!--                    <entity key="java.sql.Types.DATE" value="java.time.LocalDate"/>-->
                <!--                    <entity key="java.sql.Types.TIMESTAMP" value="java.time.Instant"/>-->
            </map>
            <!--<props>-->
            <!--<prop key="java.sql.Types.DATE">java.time.LocalDate</prop>-->
            <!--<prop key="java.sql.Types.TIMESTAMP">java.time.Instant</prop>-->
            <!--</props>-->
        </converts>
        <!--#需要移除的表名前缀,使用逗号进行分隔多个前缀,示例值: t_,tm_-->
        <prefixs>
            <list>
                <value>T_</value>
                <value>bim5d_cost_</value>
            </list>
        </prefixs>
        <!--#需要移除的表名前缀,使用逗号进行分隔多个前缀,示例值: t_,tm_-->
        <ignores>
            <list>
                <value>sys_create_time</value>
                <value>sys_modified_time</value>
                <value>sys_revision</value>
                <value>sys_creator_id</value>
                <value>sys_modifier_id</value>
            </list>
        </ignores>
        <!--#输出目录-->
        <output>out</output>
    </configuration>
</generator>

=== think-framework/think-generator/generator-swing/think-generator-swing-app/src/main/resources/generator.xml
<?xml version="1.0" encoding="UTF-8"?>
<generator xmlns="http://thinkframework.github.io/schema/generators"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
           http://thinkframework.github.io/schema/generators
           http://thinkframework.github.io/schema/generators/think-generator.xsd" id="generator">
    <strategy>
        <clazz>io.github.thinkframework.generator.core.strategy.impl.GeneratorTable</clazz>
        <responsibilitys>
            <list>
                <value>io.github.thinkframework.generator.core.chainofresponsibility.TableGeneratorResponsibility</value>
            </list>
        </responsibilitys>
    </strategy>
    <configuration>
        <!-- 框架包的名称 -->
        <frameName>com.hdhxby</frameName>
        <!--#公司名称-->
        <companyName>com.hdhxby</companyName>
        <!--#应用名称-->
        <appName>app</appName>
        <!--#模块名称-->
        <!--<moduleName>auth</moduleName>-->
        <!--<moduleName>param</moduleName>-->
        <!--            <moduleName>costenterprise</moduleName>-->
        <moduleName>costproject</moduleName>
        <!--#作者名称-->
        <!--<authorName>lixiaobin</authorName>-->
        <authorName>unascribed</authorName>
        <!--#jsp namespace: web/${namespace}/${className}/get:jsp-->
        <namespace>views</namespace>
        <!--#模板目录-->
        <!--            <template>template/glodon/enterprise</template>-->
        <!--            <template>template/glodon/project</template>-->
        <template>template/test</template>
        <!--#过滤文件-->
        <extensions>
            <list>
                <value>java</value>
                <value>js</value>
                <value>jsp</value>
                <value>xml</value>
                <value>ts</value>
                <value>html</value>
                <value>json</value>
                <value>sql</value>
            </list>
        </extensions>
        <converts>
            <map>
                <entity key="java.sql.Types.BIGINT" value="java.math.BigInteger"/>
                <!--                    <entity key="java.sql.Types.DATE" value="java.time.LocalDate"/>-->
                <!--                    <entity key="java.sql.Types.TIMESTAMP" value="java.time.Instant"/>-->
            </map>
            <!--<props>-->
            <!--<prop key="java.sql.Types.DATE">java.time.LocalDate</prop>-->
            <!--<prop key="java.sql.Types.TIMESTAMP">java.time.Instant</prop>-->
            <!--</props>-->
        </converts>
        <!--#需要移除的表名前缀,使用逗号进行分隔多个前缀,示例值: t_,tm_-->
        <prefixs>
            <list>
                <value>T_</value>
                <value>RBAC_</value>
                <value>PARAM_</value>
                <value>AUTH_</value>
                <value>PROJECT_</value>
                <value>bim5d_cost_</value>
            </list>
        </prefixs>
        <!--#需要移除的表名前缀,使用逗号进行分隔多个前缀,示例值: t_,tm_-->
        <ignores>
            <list>
                <value>sys_create_time</value>
                <value>sys_modified_time</value>
                <value>sys_revision</value>
                <value>sys_creator_id</value>
                <value>sys_modifier_id</value>
            </list>
        </ignores>
        <!--#输出目录-->
        <output>generator_output</output>
    </configuration>
</generator>
